spring.application.name=API-GATEWAY
server.port=9292

app.security.enabled=${APP_SECURITY_ENABLED:false}

eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka}
eureka.instance.hostname=${EUREKA_INSTANCE_HOSTNAME:localhost}
eureka.instance.prefer-ip-address=false

spring.cloud.gateway.routes[0].id=USER-SERVICE
spring.cloud.gateway.routes[0].uri=lb://USER-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/users/**

spring.cloud.gateway.routes[1].id=PRODUCT-SERVICE
spring.cloud.gateway.routes[1].uri=lb://PRODUCT-SERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path=/products/**

spring.cloud.gateway.routes[2].id=ORDER-SERVICE
spring.cloud.gateway.routes[2].uri=lb://ORDER-SERVICE
spring.cloud.gateway.routes[2].predicates[0]=Path=/orders/**

spring.cloud.gateway.routes[3].id=PAYMENT-SERVICE
spring.cloud.gateway.routes[3].uri=lb://PAYMENT-SERVICE
spring.cloud.gateway.routes[3].predicates[0]=Path=/payment/**

spring.cloud.gateway.routes[4].id=DELIVERY-SERVICE
spring.cloud.gateway.routes[4].uri=lb://DELIVERY-SERVICE
spring.cloud.gateway.routes[4].predicates[0]=Path=/delivery/**
