spring.application.name=PAYMENT-SERVICE
server.port=8084
eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka}
eureka.instance.hostname=${EUREKA_INSTANCE_HOSTNAME:localhost}
eureka.instance.prefer-ip-address=false

stripe.secret-key=${STRIPE_SECRET_KEY:}
app.base-url=${APP_BASE_URL:http://localhost:3000}
app.internal-api-key=${INTERNAL_API_KEY:change-me-internal}
app.worker-enqueue-url=${WORKER_ENQUEUE_URL:http://localhost:3001/internal/jobs/deliver}
